# Generated by Django 5.2.16 on 2026-08-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillgapreport",
            name="missing_skills",
            field=models.TextField(blank=True, default=""),
        ),
    ]
